cmake_minimum_required(VERSION 3.28)

set(BUILDSPEC_FILE "${CMAKE_CURRENT_SOURCE_DIR}/buildspec.json")
set(DEPS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/.deps")

macro(get_dependency_info BUILDSPEC_CONTENT DEP_NAME PLATFORM_KEY HAS_DEBUG_SYMBOLS)
  string(JSON DEP_VERSION GET "${BUILDSPEC_CONTENT}" dependencies "${DEP_NAME}" version)
  string(JSON DEP_BASEURL GET "${BUILDSPEC_CONTENT}" dependencies "${DEP_NAME}" baseUrl)
  string(JSON DEP_HASH GET "${BUILDSPEC_CONTENT}" dependencies "${DEP_NAME}" hashes "${PLATFORM_KEY}")
  if(HAS_DEBUG_SYMBOLS)
    string(
      JSON
      DEP_DEBUG_SYMBOLS_HASH
      GET "${BUILDSPEC_CONTENT}"
      dependencies
      "${DEP_NAME}"
      debugSymbols
      "${PLATFORM_KEY}"
    )
  endif()
endmacro()

if(NOT EXISTS "${BUILDSPEC_FILE}")
  message(FATAL_ERROR "buildspec.json not found at ${BUILDSPEC_FILE}")
endif()
file(READ "${BUILDSPEC_FILE}" BUILDSPEC_CONTENT)

file(MAKE_DIRECTORY "${DEPS_DIR}")

if(MSVC)
  get_dependency_info("${BUILDSPEC_CONTENT}" obs-studio windows-x64 OFF)
  get_dependency_info("${BUILDSPEC_CONTENT}" prebuilt windows-x64 OFF)
  get_dependency_info("${BUILDSPEC_CONTENT}" qt6 windows-x64 ON)
elseif(APPLE)
  set(VERSIONS_FILE "${DEPS_DIR}/.deps_versions")
  file(WRITE "${VERSIONS_FILE}" "# Auto-generated by download_deps.cmake\n")

  get_dependency_info("${BUILDSPEC_CONTENT}" obs-studio macos OFF)
  file(APPEND "${VERSIONS_FILE}" "OBS_VERSION=\"${DEP_VERSION}\"\n")
  set(FILENAME "${DEP_VERSION}.tar.gz")
  file(
    DOWNLOAD "${DEP_BASEURL}/${FILENAME}" "${DEPS_DIR}/${FILENAME}"
    EXPECTED_HASH "SHA256=${DEP_HASH}"
    STATUS DOWNLOAD_STATUS
  )
  file(ARCHIVE_EXTRACT INPUT "${DEPS_DIR}/${FILENAME}" DESTINATION "${DEPS_DIR}")

  get_dependency_info("${BUILDSPEC_CONTENT}" prebuilt macos OFF)
  file(APPEND "${VERSIONS_FILE}" "PREBUILT_VERSION=\"${DEP_VERSION}\"\n")
  set(FILENAME "macos-deps-${DEP_VERSION}-universal.tar.xz")
  file(
    DOWNLOAD "${DEP_BASEURL}/${DEP_VERSION}/${FILENAME}" "${DEPS_DIR}/${FILENAME}"
    EXPECTED_HASH "SHA256=${DEP_HASH}"
    STATUS DOWNLOAD_STATUS
  )
  file(ARCHIVE_EXTRACT INPUT "${DEPS_DIR}/${FILENAME}" DESTINATION "${DEPS_DIR}/obs-deps-${DEP_VERSION}-universal")

  get_dependency_info("${BUILDSPEC_CONTENT}" qt6 macos ON)
  file(APPEND "${VERSIONS_FILE}" "QT6_VERSION=\"${DEP_VERSION}\"\n")
  set(FILENAME "macos-deps-qt6-${DEP_VERSION}-universal.tar.xz")
  file(
    DOWNLOAD "${DEP_BASEURL}/${DEP_VERSION}/${FILENAME}" "${DEPS_DIR}/${FILENAME}"
    EXPECTED_HASH "SHA256=${DEP_HASH}"
    STATUS DOWNLOAD_STATUS
  )
  file(ARCHIVE_EXTRACT INPUT "${DEPS_DIR}/${FILENAME}" DESTINATION "${DEPS_DIR}/obs-deps-qt6-${DEP_VERSION}-universal")

  execute_process(
    COMMAND xattr -r -d com.apple.quarantine "${DEPS_DIR}"
    RESULT_VARIABLE XATTR_RESULT
    OUTPUT_QUIET
    ERROR_QUIET
  )
else()
  message(FATAL_ERROR "This script must not be run on this platform.")
endif()

message(STATUS "All dependencies downloaded and extracted to ${DEPS_DIR}")
