name: Set up macOS Signing Certificates
description: Imports the macOS code signing certificate into a temporary keychain

inputs:
  MACOS_SIGNING_CERT:
    description: Base64 encoded .p12 certificate
    required: true
  MACOS_SIGNING_CERT_PASSWORD:
    description: Password for the .p12 certificate
    required: true

runs:
  using: "composite"
  steps:
    - name: Import Signing Certificate
      shell: bash
      env:
        CERT_B64: ${{ inputs.MACOS_SIGNING_CERT }}
        CERT_PWD: ${{ inputs.MACOS_SIGNING_CERT_PASSWORD }}
        KEYCHAIN_PATH: ${{ runner.temp }}/app-signing.keychain-db
      run: |
        KEYCHAIN_PASSWORD=$(openssl rand -base64 32)

        security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
        security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

        base64 --decode <<< "$CERT_B64" > certificate.p12
        security import certificate.p12 -k "$KEYCHAIN_PATH" -P "$CERT_PWD" -T /usr/bin/codesign
        rm certificate.p12

        security list-keychains -s "$KEYCHAIN_PATH"
